# Dependencies
markdown:	      kramdown
highlighter:	  rouge

# Permalinks
permalink:        pretty

# Setup
title:            Breandan's Blog 
tagline:          
description:       
url:              breandan.net
comments:         false
author:
  name:           Breandan Considine
  url:            https://twitter.com/breandan

paginate:         1

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/breandan/breandan.github.io

# Gems
gems: [jekyll-paginate]